CREATE TABLE IF NOT EXISTS test
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    active TINYINT      NOT NULL,
    time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;